### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [michael-77/christopher-morley_the-haunted-bookshop#1]
- Remove abbr.name from signature in dedication
- Header in dedication needs styling: text-align: center; font-variant: small-caps; margin: 1em 0;
- In endnote #2, wrap CDM in <cite>, and add an em-dash before the abbr (but within cite)
- Let's add padding: 1em to blockquote.sign and change blockquote.placard to be padding: 1em too for consistency
- Instead of blockquote.booklist, use a `ul` element. You can style it to remove the bullets.
- Instead of p.headline, use `<header><p>...` Usually headlines are also centered, is this the case in the scans?
- Don't use `<hr>` in signs if you need a horizontal rule. For example in Chapter 5. The semantics of `<hr>` are "thematic break" and shouldn't be used just for styling. You can imitate an `<hr>` by targeting the specific elements that need a rule and adding a pseudo-element before it, or with a simple border-top.
- Usually `<em>` is not appropriate in blockquotes that are signs; `<em>` means emphasized speech, and signs can't have emphatic speech. Instead you can use `<b>` with `font-weight: normal; font-variant: small-caps;`.
- I'm confused about the styling for `blockquote.placard p + p`. Why are we doing poetry-style indents for this?
- In colophon, remove comma before "and the online distributed..."
- Capitalize name of painting

Content.opf:
- Missing dc:source for scans
- dc:description must be a single sentence that describes/summarizes the work. See other ebooks for examples.
- use `<em>` in long-description instead of `<i>`
- Missing distributed proofreaders in metadata; see other Dracula for example

**Comment by michael-77** [comment]
Headlines were centered in the original and so have been targetted for centering in local.css 
Poetry-style indentation has been removed although some of the short boxes now use text-indent: 0 to keep them consistent with the scans.

**Comment by michael-77** [comment]
#d7922dc
